image: node:13.10.1

stages:
  - install
  - deploy
  
before_script:
  - npm install

cache:
  paths:
    - node_modules/

run:
  stage: deploy
  script:
    - node index.js $POST_URL $KEY
  artifacts:
    paths:
    - public
  only:
  - master
