image: node:13.10.1

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - .npm/
  - node_modules/

pages:
  stage: deploy
  script:
    - npm i
    - node $POST_URL $KEY
  artifacts:
    paths:
    - public
  only:
  - master
