stages:
  - dependencies
  - deploy

cache:
  paths:
    - node_modules/

dependencies:
  stage: dependencies
  image: docker
  variables:
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker build -t bostrot/who-crawler-dependencies .
  only:
  - master
  tags: [docker]

deploy:
  image: bostrot/who-crawler-dependencies:latest
  stage: deploy
  script:
    - npm install
    - node index.js $POST_URL $KEY $IMGUR
    - pwd
    - ls
  artifacts:
    paths:
    - public
  only:
  - master
  tags: [docker]
