image: bostrot/who-crawler-dependencies:latest

stages:
  - install
  - deploy
  
before_script:
  - npm install

cache:
  paths:
    - node_modules/

run:
  stage: deploy
  script:
    - node index.js $POST_URL $KEY $IMGUR
    - pwd
    - ls
  artifacts:
    paths:
    - public
  only:
  - master
  tags: [docker]
