image: node:13.10.1

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - .npm/
  - node_modules/

install_packages:
  stage: install
  script:
    - npm prune
    - npm install
  cache:
    key: ${CI_BUILD_REF_NAME}
    paths:
      - node_modules/
  artifacts:
    paths:
      - node_modules/
  only:
    refs:
      - master
      - develop
    changes:
      - package.json

run:
  stage: deploy
  script:
    - node $POST_URL $KEY
  artifacts:
    paths:
    - public
  only:
  - master
