image: node:13.10.1

stages:
  - install
  - deploy

install_packages:
  stage: install
  script:
    - npm prune
    - npm install
  cache:
    key: ${CI_BUILD_REF_NAME}
    paths:
      - node_modules/
  artifacts:
    paths:
      - node_modules/
  only:
    refs:
      - master
      - develop
    changes:
      - package.json

run:
  stage: deploy
  script:
    - ls
    - echo $POST_URL $KEY
    - node $POST_URL $KEY
  artifacts:
    paths:
    - public
  only:
  - master
